from tkinter import *
from turtle import right
root=Tk()#here i made a gui
def totalprise():
    total=int(e1.get())*60 + int(e2.get())*30 + int(e3.get())*7+int(e4.get())*100 + int(e5.get())*20 + int(e6.get())*15+int(e7.get())*7
    bill.set(total)
    
root.geometry("1000x500")
root.minsize(width=1000,height=500)
root.maxsize(width=1000,height=500)
top_frame=Frame(root,bg="black",width=1000,height=100)
top_frame.place(x=0,y=0)
Label(top_frame,text="BILL MANAGEMENT",font="lucida 20 bold",fg="white",bg="black").place(x=380,y=30)


side_frame=Frame(root,width=333,height=390,bg="lime",borderwidth=5,relief="groove")
Label(side_frame,text="Menu",font="castellar 20 bold",bg="lime").place(x=111,y=20)
Label(side_frame,text="Dosa.....................Rs.60/Plate",font="Gabriola 15 bold",bg="lime").place(x=10,y=50)
Label(side_frame,text="Cookies..................Rs.30/Plate",font="Gabriola 15 bold",bg="lime").place(x=10,y=80)
Label(side_frame,text="Tea..................Rs.7/Cup",font="Gabriola 15 bold",bg="lime").place(x=10,y=110)
Label(side_frame,text="Coffee..................Rs.100/Cup",font="Gabriola 15 bold",bg="lime").place(x=10,y=140)
Label(side_frame,text="Juice..................Rs.20/Glass",font="Gabriola 15 bold",bg="lime").place(x=10,y=170)
Label(side_frame,text="Pancakes..................Rs.15/Pack",font="Gabriola 15 bold",bg="lime").place(x=10,y=200)
Label(side_frame,text="Eggs..................Rs.7/Egg",font="Gabriola 15 bold",bg="lime").place(x=10,y=230)
side_frame.place(x=5,y=105)

middle_frame=Frame(root,height=390,width=333,bg="gold",borderwidth=5,relief="groove")
Label(middle_frame,font="lucida 15 bold",text="Dosa",bg="gold",).place(x=10,y=10)
Label(middle_frame,font="lucida 15 bold",text="Cookies",bg="gold").place(x=10,y=50)
Label(middle_frame,font="lucida 15 bold",text="Tea",bg="gold").place(x=10,y=90)
Label(middle_frame,font="lucida 15 bold",text="Coffeee",bg="gold").place(x=10,y=130)
Label(middle_frame,font="lucida 15 bold",text="juice",bg="gold").place(x=10,y=170)
Label(middle_frame,font="lucida 15 bold",text="Pancakes",bg="gold").place(x=10,y=210)
Label(middle_frame,font="lucida 15 bold",text="Eggs",bg="gold").place(x=10,y=250)
dosa=IntVar()
cookies=IntVar()
tea=IntVar()
coffee=IntVar()
juice=IntVar()
pancakes=IntVar()
eggs=IntVar()
e1=Entry(middle_frame,textvariable=dosa,font="lucida 15 bold",width=10,bg="pink")
e1.place(x=200,y=10)
e2=Entry(middle_frame,textvariable=cookies,font="lucida 15 bold",width=10,bg="pink")
e2.place(x=200,y=50)
e3=Entry(middle_frame,textvariable=tea,font="lucida 15 bold",width=10,bg="pink")
e3.place(x=200,y=90)
e4=Entry(middle_frame,textvariable=coffee,font="lucida 15 bold",width=10,bg="pink")
e4.place(x=200,y=130)
e5=Entry(middle_frame,textvariable=juice,font="lucida 15 bold",width=10,bg="pink")
e5.place(x=200,y=170)
e6=Entry(middle_frame,textvariable=pancakes,font="lucida 15 bold",width=10,bg="pink")
e6.place(x=200,y=210)
e7=Entry(middle_frame,textvariable=eggs,font="lucida 15 bold",width=10,bg="pink")
e7.place(x=200,y=250)
reset=Button(middle_frame,text="RESET",font="halvetica 10 bold",bg="aqua",cursor="hand2").place(x=10,y=300)
total=Button(middle_frame,text="TOTAL",font="halvetica 10 bold",bg="aqua",cursor="hand2",command=totalprise).place(x=200,y=300)
middle_frame.place(x=340,y=105)
right_frame=Frame(root,height=390,width=330,bg="aqua",borderwidth=5,relief="groove")
Label(right_frame,text="BILL",font="castellar 20 bold",bg="aqua").place(x=130,y=20)
Label(right_frame,text="TOTAL",font="lucida 20 bold",bg="aqua").place(x=120,y=60)
bill=IntVar()
e8=Entry(right_frame,textvariable=bill,font="lucida 15 bold")
e8.place(x=50,y=120)


right_frame.place(x=670,y=105)
root.mainloop()